from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1082, 666)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(250, 10, 631, 71))
        self.label.setStyleSheet("font: 75 22pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(130, 480, 311, 71))
        self.pushButton.setStyleSheet("font: 22pt \"MS Shell Dlg 2\";")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(630, 480, 311, 71))
        self.pushButton_2.setStyleSheet("font: 22pt \"MS Shell Dlg 2\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 90, 961, 361))
        self.label_2.setStyleSheet("border: 1px solid red;")
        self.label_2.setText("")

        self.pixmap = QPixmap("bg_2.png")
        self.label_2.setPixmap(self.pixmap)

        self.label_2.setObjectName("label_2")
        self.loginFrame = QtWidgets.QFrame(self.centralwidget)
        self.loginFrame.setGeometry(QtCore.QRect(0, 0, 1081, 611))
        self.loginFrame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.loginFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.loginFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.loginFrame.setObjectName("loginFrame")
        self.label_3 = QtWidgets.QLabel(self.loginFrame)
        self.label_3.setGeometry(QtCore.QRect(370, 10, 351, 71))
        self.label_3.setStyleSheet("font: 26pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.loginFrame)
        self.label_4.setGeometry(QtCore.QRect(80, 140, 331, 61))
        self.label_4.setStyleSheet("font: 22pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.loginFrame)
        self.label_5.setGeometry(QtCore.QRect(80, 250, 331, 61))
        self.label_5.setStyleSheet("font: 22pt \"MS Shell Dlg 2\";")
        self.label_5.setObjectName("label_5")
        self.login_id = QtWidgets.QLineEdit(self.loginFrame)
        self.login_id.setGeometry(QtCore.QRect(490, 150, 411, 51))
        self.login_id.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.login_id.setObjectName("login_id")
        self.login_pwd = QtWidgets.QLineEdit(self.loginFrame)
        self.login_pwd.setGeometry(QtCore.QRect(490, 260, 411, 51))
        self.login_pwd.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.login_pwd.setObjectName("login_pwd")
        self.login_btn = QtWidgets.QPushButton(self.loginFrame)
        self.login_btn.setGeometry(QtCore.QRect(340, 440, 371, 71))
        self.login_btn.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.login_btn.setObjectName("login_btn")
        self.registerFrame = QtWidgets.QFrame(self.centralwidget)
        self.registerFrame.setGeometry(QtCore.QRect(10, 0, 1081, 611))
        self.registerFrame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.registerFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.registerFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.registerFrame.setObjectName("registerFrame")
        self.label_9 = QtWidgets.QLabel(self.registerFrame)
        self.label_9.setGeometry(QtCore.QRect(370, 10, 441, 71))
        self.label_9.setStyleSheet("font: 26pt \"MS Shell Dlg 2\";")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.registerFrame)
        self.label_10.setGeometry(QtCore.QRect(80, 140, 331, 61))
        self.label_10.setStyleSheet("font: 22pt \"MS Shell Dlg 2\";")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.registerFrame)
        self.label_11.setGeometry(QtCore.QRect(80, 220, 331, 61))
        self.label_11.setStyleSheet("font: 22pt \"MS Shell Dlg 2\";")
        self.label_11.setObjectName("label_11")
        self.reg_id = QtWidgets.QLineEdit(self.registerFrame)
        self.reg_id.setGeometry(QtCore.QRect(490, 150, 411, 51))
        self.reg_id.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.reg_id.setObjectName("reg_id")
        self.reg_name = QtWidgets.QLineEdit(self.registerFrame)
        self.reg_name.setGeometry(QtCore.QRect(490, 230, 411, 51))
        self.reg_name.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.reg_name.setObjectName("reg_name")
        self.reg_btn = QtWidgets.QPushButton(self.registerFrame)
        self.reg_btn.setGeometry(QtCore.QRect(340, 510, 371, 71))
        self.reg_btn.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.reg_btn.setObjectName("reg_btn")
        self.reg_pwd = QtWidgets.QLineEdit(self.registerFrame)
        self.reg_pwd.setGeometry(QtCore.QRect(490, 310, 411, 51))
        self.reg_pwd.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.reg_pwd.setObjectName("reg_pwd")
        self.label_12 = QtWidgets.QLabel(self.registerFrame)
        self.label_12.setGeometry(QtCore.QRect(80, 300, 331, 61))
        self.label_12.setStyleSheet("font: 22pt \"MS Shell Dlg 2\";")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.registerFrame)
        self.label_13.setGeometry(QtCore.QRect(80, 380, 331, 61))
        self.label_13.setStyleSheet("font: 22pt \"MS Shell Dlg 2\";")
        self.label_13.setObjectName("label_13")
        self.reg_dept = QtWidgets.QComboBox(self.registerFrame)
        self.reg_dept.setGeometry(QtCore.QRect(490, 390, 411, 51))
        self.reg_dept.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.reg_dept.setObjectName("reg_dept")
        self.reg_dept.addItem("")
        self.reg_dept.addItem("")
        self.reg_dept.addItem("")
        self.reg_dept.addItem("")
        self.reg_dept.addItem("")
        self.reg_dept.addItem("")
        self.reg_dept.addItem("")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 10, 1071, 611))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_16 = QtWidgets.QLabel(self.frame)
        self.label_16.setGeometry(QtCore.QRect(380, 10, 441, 71))
        self.label_16.setStyleSheet("font: 26pt \"MS Shell Dlg 2\";")
        self.label_16.setObjectName("label_16")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.frame)
        self.tableWidget_3.setGeometry(QtCore.QRect(50, 140, 421, 351))
        self.tableWidget_3.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(1)
        self.tableWidget_3.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(0, 0, item)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1082, 26))
        self.menubar.setObjectName("menubar")
        self.menuEmployee_Login = QtWidgets.QMenu(self.menubar)
        self.menuEmployee_Login.setObjectName("menuEmployee_Login")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLogin = QtWidgets.QAction(MainWindow)
        self.actionLogin.setObjectName("actionLogin")
        self.actionRegister = QtWidgets.QAction(MainWindow)
        self.actionRegister.setObjectName("actionRegister")
        self.menuEmployee_Login.addAction(self.actionLogin)
        self.menuEmployee_Login.addAction(self.actionRegister)
        self.menubar.addAction(self.menuEmployee_Login.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "EMS - Employee Management System"))
        self.pushButton.setText(_translate("MainWindow", "Login"))
        self.pushButton_2.setText(_translate("MainWindow", "Register"))
        self.label_3.setText(_translate("MainWindow", "Employee Login"))
        self.label_4.setText(_translate("MainWindow", "Enter Employee ID"))
        self.label_5.setText(_translate("MainWindow", "Enter Password"))
        self.login_btn.setText(_translate("MainWindow", "Login"))
        self.label_9.setText(_translate("MainWindow", "Employee Registration"))
        self.label_10.setText(_translate("MainWindow", "Enter Employee ID"))
        self.label_11.setText(_translate("MainWindow", "Enter Name"))
        self.reg_btn.setText(_translate("MainWindow", "Register"))
        self.label_12.setText(_translate("MainWindow", "Enter Password"))
        self.label_13.setText(_translate("MainWindow", "Enter Department"))
        self.reg_dept.setItemText(0, _translate("MainWindow", "IT"))
        self.reg_dept.setItemText(1, _translate("MainWindow", "HR"))
        self.reg_dept.setItemText(2, _translate("MainWindow", "Sales"))
        self.reg_dept.setItemText(3, _translate("MainWindow", "Finance"))
        self.reg_dept.setItemText(4, _translate("MainWindow", "Marketing"))
        self.reg_dept.setItemText(5, _translate("MainWindow", "Operations"))
        self.reg_dept.setItemText(6, _translate("MainWindow", "Management"))
        self.label_16.setText(_translate("MainWindow", "Emploee Home"))
        item = self.tableWidget_3.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Emp ID"))
        item = self.tableWidget_3.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Emp Name"))
        item = self.tableWidget_3.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Emp Dept"))
        item = self.tableWidget_3.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Emp Salary"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Details"))
        __sortingEnabled = self.tableWidget_3.isSortingEnabled()
        self.tableWidget_3.setSortingEnabled(False)
        self.tableWidget_3.setSortingEnabled(__sortingEnabled)
        self.menuEmployee_Login.setTitle(_translate("MainWindow", "Employee Login"))
        self.actionLogin.setText(_translate("MainWindow", "Login"))
        self.actionRegister.setText(_translate("MainWindow", "Register"))

        self.frame.hide()
        self.loginFrame.hide()
        self.registerFrame.hide()

        self.pushButton.clicked.connect(self.showLoginPage)
        self.pushButton_2.clicked.connect(self.showRegisterPage)

    def showLoginPage(self):
        self.loginFrame.show()

    def showRegisterPage(self):
        self.registerFrame.show()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

